"""ODME Python SDK — read ODD models exported by ODME."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Union
from .model import Project

__version__ = "1.0.0"


def load_project(path: Union[str, Path]) -> Project:
    """Load an ODME project export JSON file.

    Args:
        path: Path to the project_export.json file generated by ODME.

    Returns:
        A Project object with the complete ODD model, scenarios,
        parameters, test cases, coverage, and traceability data.

    Example::

        import odme

        project = odme.load_project("plugin_export.json")
        for leaf in project.ses_tree.root.leaf_nodes():
            print(f"{leaf.path}: {leaf.variables}")
    """
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return Project.from_dict(data)
